br_require: 0
br_list_title: 'Revision type'
br_list_options: "New input\nCopy changes\nCorrecting missing/wrong information"
br_list_help: ''
br_add_text: 0
br_area_title: 'Explanation of revision'
_core:
  default_config_hash: m3L3ZTIH_3_9ebBDJnyOKI8POQGvI-nHDknyhV0mGBg
